---
abstract: 'Tamper-resistant HTTP Cookies'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Data::Dumper: 0
  File::Spec::Functions: 0
  HTTP::Headers::Util: 0
  HTTP::Request::Common: 0
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-HashedCookies
requires:
  CGI::Simple::Cookie: 0
  Catalyst::Request: 0
  Digest::HMAC_MD5: 0
  Digest::HMAC_SHA1: 0
  MRO::Compat: 0
  Symbol: 0
  Tie::IxHash: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-HashedCookies
  homepage: https://github.com/ollyg/Catalyst-Plugin-HashedCookies/wiki
  repository: git://github.com/ollyg/Catalyst-Plugin-HashedCookies.git
version: 1.131710
